server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment
#    consule注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_database?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource