server:
  port: 8007

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_database?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  #  开启mp日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    扫描 resource 里的 xml 文件
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
eureka:
  client:
    #    自己是否注册进eureka服务器
    register-with-eureka: true
    #    是否从eureka服务器中抓去已有注册信息 单节点无所谓 集群必须设置为true才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      #      只需一个eureka服务地址即可
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


