server:
  port: 80

spring:
  application:
    name: cloud-order-hystrix-feign-service

eureka:
  client:
    #    自己是否注册进eureka服务器
    register-with-eureka: true
    #    是否从eureka服务器中抓去已有注册信息 单节点无所谓 集群必须设置为true才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# feign客户端超时时间 超过改时间限制报错timeout
ribbon:
  #  建立连接后 读取到可用资源 时间
  ReadTimeout: 5000
  #  建立连接所有用时间
  ConnnectTimeout: 5000


logging:
  level:
    com.my.springcloud.service.PaymentService: debug
feign:
  hystrix:
    enabled: true
